/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as PartnershipsRouteImport } from './routes/partnerships'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesTherapyRouteImport } from './routes/services_.therapy'
import { Route as ServicesMedicationManagementRouteImport } from './routes/services_.medication-management'
import { Route as ServicesIopRouteImport } from './routes/services_.iop'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnershipsRoute = PartnershipsRouteImport.update({
  id: '/partnerships',
  path: '/partnerships',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesTherapyRoute = ServicesTherapyRouteImport.update({
  id: '/services_/therapy',
  path: '/services/therapy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMedicationManagementRoute =
  ServicesMedicationManagementRouteImport.update({
    id: '/services_/medication-management',
    path: '/services/medication-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesIopRoute = ServicesIopRouteImport.update({
  id: '/services_/iop',
  path: '/services/iop',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/community': typeof CommunityRoute
  '/partnerships': typeof PartnershipsRoute
  '/providers': typeof ProvidersRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/iop': typeof ServicesIopRoute
  '/services/medication-management': typeof ServicesMedicationManagementRoute
  '/services/therapy': typeof ServicesTherapyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/community': typeof CommunityRoute
  '/partnerships': typeof PartnershipsRoute
  '/providers': typeof ProvidersRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/iop': typeof ServicesIopRoute
  '/services/medication-management': typeof ServicesMedicationManagementRoute
  '/services/therapy': typeof ServicesTherapyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/community': typeof CommunityRoute
  '/partnerships': typeof PartnershipsRoute
  '/providers': typeof ProvidersRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services_/iop': typeof ServicesIopRoute
  '/services_/medication-management': typeof ServicesMedicationManagementRoute
  '/services_/therapy': typeof ServicesTherapyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/booking'
    | '/community'
    | '/partnerships'
    | '/providers'
    | '/services'
    | '/sitemap.xml'
    | '/services/iop'
    | '/services/medication-management'
    | '/services/therapy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booking'
    | '/community'
    | '/partnerships'
    | '/providers'
    | '/services'
    | '/sitemap.xml'
    | '/services/iop'
    | '/services/medication-management'
    | '/services/therapy'
  id:
    | '__root__'
    | '/'
    | '/booking'
    | '/community'
    | '/partnerships'
    | '/providers'
    | '/services'
    | '/sitemap.xml'
    | '/services_/iop'
    | '/services_/medication-management'
    | '/services_/therapy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingRoute: typeof BookingRoute
  CommunityRoute: typeof CommunityRoute
  PartnershipsRoute: typeof PartnershipsRoute
  ProvidersRoute: typeof ProvidersRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ServicesIopRoute: typeof ServicesIopRoute
  ServicesMedicationManagementRoute: typeof ServicesMedicationManagementRoute
  ServicesTherapyRoute: typeof ServicesTherapyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partnerships': {
      id: '/partnerships'
      path: '/partnerships'
      fullPath: '/partnerships'
      preLoaderRoute: typeof PartnershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/therapy': {
      id: '/services_/therapy'
      path: '/services/therapy'
      fullPath: '/services/therapy'
      preLoaderRoute: typeof ServicesTherapyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/medication-management': {
      id: '/services_/medication-management'
      path: '/services/medication-management'
      fullPath: '/services/medication-management'
      preLoaderRoute: typeof ServicesMedicationManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/iop': {
      id: '/services_/iop'
      path: '/services/iop'
      fullPath: '/services/iop'
      preLoaderRoute: typeof ServicesIopRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingRoute: BookingRoute,
  CommunityRoute: CommunityRoute,
  PartnershipsRoute: PartnershipsRoute,
  ProvidersRoute: ProvidersRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ServicesIopRoute: ServicesIopRoute,
  ServicesMedicationManagementRoute: ServicesMedicationManagementRoute,
  ServicesTherapyRoute: ServicesTherapyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
