/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as VirtualWellnessRouteImport } from './routes/virtual-wellness'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as ProviderApplyRouteImport } from './routes/provider-apply'
import { Route as PartnershipsRouteImport } from './routes/partnerships'
import { Route as JoinTheNetworkRouteImport } from './routes/join-the-network'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as GetMatchedRouteImport } from './routes/get-matched'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesVirtualBehavioralHealthRouteImport } from './routes/services_.virtual-behavioral-health'
import { Route as ServicesTherapyRouteImport } from './routes/services_.therapy'
import { Route as ServicesProviderPartnershipsRouteImport } from './routes/services_.provider-partnerships'
import { Route as ServicesPeptideWellnessRouteImport } from './routes/services_.peptide-wellness'
import { Route as ServicesMentalHealthRouteImport } from './routes/services_.mental-health'
import { Route as ServicesMedicationManagementRouteImport } from './routes/services_.medication-management'
import { Route as ServicesIopRouteImport } from './routes/services_.iop'
import { Route as ServicesHealthcareConsultingRouteImport } from './routes/services_.healthcare-consulting'
import { Route as ServicesCoachingDevelopmentRouteImport } from './routes/services_.coaching-development'
import { Route as ServicesCoachingRouteImport } from './routes/services_.coaching'
import { Route as ServicesClinicalRouteImport } from './routes/services_.clinical'

const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const VirtualWellnessRoute = VirtualWellnessRouteImport.update({
  id: '/virtual-wellness',
  path: '/virtual-wellness',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderApplyRoute = ProviderApplyRouteImport.update({
  id: '/provider-apply',
  path: '/provider-apply',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnershipsRoute = PartnershipsRouteImport.update({
  id: '/partnerships',
  path: '/partnerships',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTheNetworkRoute = JoinTheNetworkRouteImport.update({
  id: '/join-the-network',
  path: '/join-the-network',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const GetMatchedRoute = GetMatchedRouteImport.update({
  id: '/get-matched',
  path: '/get-matched',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesVirtualBehavioralHealthRoute =
  ServicesVirtualBehavioralHealthRouteImport.update({
    id: '/services_/virtual-behavioral-health',
    path: '/services/virtual-behavioral-health',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesTherapyRoute = ServicesTherapyRouteImport.update({
  id: '/services_/therapy',
  path: '/services/therapy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesProviderPartnershipsRoute =
  ServicesProviderPartnershipsRouteImport.update({
    id: '/services_/provider-partnerships',
    path: '/services/provider-partnerships',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesPeptideWellnessRoute = ServicesPeptideWellnessRouteImport.update({
  id: '/services_/peptide-wellness',
  path: '/services/peptide-wellness',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMentalHealthRoute = ServicesMentalHealthRouteImport.update({
  id: '/services_/mental-health',
  path: '/services/mental-health',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMedicationManagementRoute =
  ServicesMedicationManagementRouteImport.update({
    id: '/services_/medication-management',
    path: '/services/medication-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesIopRoute = ServicesIopRouteImport.update({
  id: '/services_/iop',
  path: '/services/iop',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesHealthcareConsultingRoute =
  ServicesHealthcareConsultingRouteImport.update({
    id: '/services_/healthcare-consulting',
    path: '/services/healthcare-consulting',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesCoachingDevelopmentRoute =
  ServicesCoachingDevelopmentRouteImport.update({
    id: '/services_/coaching-development',
    path: '/services/coaching-development',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesCoachingRoute = ServicesCoachingRouteImport.update({
  id: '/services_/coaching',
  path: '/services/coaching',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesClinicalRoute = ServicesClinicalRouteImport.update({
  id: '/services_/clinical',
  path: '/services/clinical',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/get-matched': typeof GetMatchedRoute
  '/intake': typeof IntakeRoute
  '/join-the-network': typeof JoinTheNetworkRoute
  '/partnerships': typeof PartnershipsRoute
  '/provider-apply': typeof ProviderApplyRoute
  '/providers': typeof ProvidersRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/virtual-wellness': typeof VirtualWellnessRoute
  '/waitlist': typeof WaitlistRoute
  '/services/clinical': typeof ServicesClinicalRoute
  '/services/coaching': typeof ServicesCoachingRoute
  '/services/coaching-development': typeof ServicesCoachingDevelopmentRoute
  '/services/healthcare-consulting': typeof ServicesHealthcareConsultingRoute
  '/services/iop': typeof ServicesIopRoute
  '/services/medication-management': typeof ServicesMedicationManagementRoute
  '/services/mental-health': typeof ServicesMentalHealthRoute
  '/services/peptide-wellness': typeof ServicesPeptideWellnessRoute
  '/services/provider-partnerships': typeof ServicesProviderPartnershipsRoute
  '/services/therapy': typeof ServicesTherapyRoute
  '/services/virtual-behavioral-health': typeof ServicesVirtualBehavioralHealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/get-matched': typeof GetMatchedRoute
  '/intake': typeof IntakeRoute
  '/join-the-network': typeof JoinTheNetworkRoute
  '/partnerships': typeof PartnershipsRoute
  '/provider-apply': typeof ProviderApplyRoute
  '/providers': typeof ProvidersRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/virtual-wellness': typeof VirtualWellnessRoute
  '/waitlist': typeof WaitlistRoute
  '/services/clinical': typeof ServicesClinicalRoute
  '/services/coaching': typeof ServicesCoachingRoute
  '/services/coaching-development': typeof ServicesCoachingDevelopmentRoute
  '/services/healthcare-consulting': typeof ServicesHealthcareConsultingRoute
  '/services/iop': typeof ServicesIopRoute
  '/services/medication-management': typeof ServicesMedicationManagementRoute
  '/services/mental-health': typeof ServicesMentalHealthRoute
  '/services/peptide-wellness': typeof ServicesPeptideWellnessRoute
  '/services/provider-partnerships': typeof ServicesProviderPartnershipsRoute
  '/services/therapy': typeof ServicesTherapyRoute
  '/services/virtual-behavioral-health': typeof ServicesVirtualBehavioralHealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/get-matched': typeof GetMatchedRoute
  '/intake': typeof IntakeRoute
  '/join-the-network': typeof JoinTheNetworkRoute
  '/partnerships': typeof PartnershipsRoute
  '/provider-apply': typeof ProviderApplyRoute
  '/providers': typeof ProvidersRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/virtual-wellness': typeof VirtualWellnessRoute
  '/waitlist': typeof WaitlistRoute
  '/services_/clinical': typeof ServicesClinicalRoute
  '/services_/coaching': typeof ServicesCoachingRoute
  '/services_/coaching-development': typeof ServicesCoachingDevelopmentRoute
  '/services_/healthcare-consulting': typeof ServicesHealthcareConsultingRoute
  '/services_/iop': typeof ServicesIopRoute
  '/services_/medication-management': typeof ServicesMedicationManagementRoute
  '/services_/mental-health': typeof ServicesMentalHealthRoute
  '/services_/peptide-wellness': typeof ServicesPeptideWellnessRoute
  '/services_/provider-partnerships': typeof ServicesProviderPartnershipsRoute
  '/services_/therapy': typeof ServicesTherapyRoute
  '/services_/virtual-behavioral-health': typeof ServicesVirtualBehavioralHealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/booking'
    | '/community'
    | '/contact'
    | '/get-matched'
    | '/intake'
    | '/join-the-network'
    | '/partnerships'
    | '/provider-apply'
    | '/providers'
    | '/services'
    | '/sitemap.xml'
    | '/virtual-wellness'
    | '/waitlist'
    | '/services/clinical'
    | '/services/coaching'
    | '/services/coaching-development'
    | '/services/healthcare-consulting'
    | '/services/iop'
    | '/services/medication-management'
    | '/services/mental-health'
    | '/services/peptide-wellness'
    | '/services/provider-partnerships'
    | '/services/therapy'
    | '/services/virtual-behavioral-health'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/booking'
    | '/community'
    | '/contact'
    | '/get-matched'
    | '/intake'
    | '/join-the-network'
    | '/partnerships'
    | '/provider-apply'
    | '/providers'
    | '/services'
    | '/sitemap.xml'
    | '/virtual-wellness'
    | '/waitlist'
    | '/services/clinical'
    | '/services/coaching'
    | '/services/coaching-development'
    | '/services/healthcare-consulting'
    | '/services/iop'
    | '/services/medication-management'
    | '/services/mental-health'
    | '/services/peptide-wellness'
    | '/services/provider-partnerships'
    | '/services/therapy'
    | '/services/virtual-behavioral-health'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/booking'
    | '/community'
    | '/contact'
    | '/get-matched'
    | '/intake'
    | '/join-the-network'
    | '/partnerships'
    | '/provider-apply'
    | '/providers'
    | '/services'
    | '/sitemap.xml'
    | '/virtual-wellness'
    | '/waitlist'
    | '/services_/clinical'
    | '/services_/coaching'
    | '/services_/coaching-development'
    | '/services_/healthcare-consulting'
    | '/services_/iop'
    | '/services_/medication-management'
    | '/services_/mental-health'
    | '/services_/peptide-wellness'
    | '/services_/provider-partnerships'
    | '/services_/therapy'
    | '/services_/virtual-behavioral-health'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookingRoute: typeof BookingRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  GetMatchedRoute: typeof GetMatchedRoute
  IntakeRoute: typeof IntakeRoute
  JoinTheNetworkRoute: typeof JoinTheNetworkRoute
  PartnershipsRoute: typeof PartnershipsRoute
  ProviderApplyRoute: typeof ProviderApplyRoute
  ProvidersRoute: typeof ProvidersRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VirtualWellnessRoute: typeof VirtualWellnessRoute
  WaitlistRoute: typeof WaitlistRoute
  ServicesClinicalRoute: typeof ServicesClinicalRoute
  ServicesCoachingRoute: typeof ServicesCoachingRoute
  ServicesCoachingDevelopmentRoute: typeof ServicesCoachingDevelopmentRoute
  ServicesHealthcareConsultingRoute: typeof ServicesHealthcareConsultingRoute
  ServicesIopRoute: typeof ServicesIopRoute
  ServicesMedicationManagementRoute: typeof ServicesMedicationManagementRoute
  ServicesMentalHealthRoute: typeof ServicesMentalHealthRoute
  ServicesPeptideWellnessRoute: typeof ServicesPeptideWellnessRoute
  ServicesProviderPartnershipsRoute: typeof ServicesProviderPartnershipsRoute
  ServicesTherapyRoute: typeof ServicesTherapyRoute
  ServicesVirtualBehavioralHealthRoute: typeof ServicesVirtualBehavioralHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/virtual-wellness': {
      id: '/virtual-wellness'
      path: '/virtual-wellness'
      fullPath: '/virtual-wellness'
      preLoaderRoute: typeof VirtualWellnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider-apply': {
      id: '/provider-apply'
      path: '/provider-apply'
      fullPath: '/provider-apply'
      preLoaderRoute: typeof ProviderApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partnerships': {
      id: '/partnerships'
      path: '/partnerships'
      fullPath: '/partnerships'
      preLoaderRoute: typeof PartnershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-the-network': {
      id: '/join-the-network'
      path: '/join-the-network'
      fullPath: '/join-the-network'
      preLoaderRoute: typeof JoinTheNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-matched': {
      id: '/get-matched'
      path: '/get-matched'
      fullPath: '/get-matched'
      preLoaderRoute: typeof GetMatchedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/virtual-behavioral-health': {
      id: '/services_/virtual-behavioral-health'
      path: '/services/virtual-behavioral-health'
      fullPath: '/services/virtual-behavioral-health'
      preLoaderRoute: typeof ServicesVirtualBehavioralHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/therapy': {
      id: '/services_/therapy'
      path: '/services/therapy'
      fullPath: '/services/therapy'
      preLoaderRoute: typeof ServicesTherapyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/provider-partnerships': {
      id: '/services_/provider-partnerships'
      path: '/services/provider-partnerships'
      fullPath: '/services/provider-partnerships'
      preLoaderRoute: typeof ServicesProviderPartnershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/peptide-wellness': {
      id: '/services_/peptide-wellness'
      path: '/services/peptide-wellness'
      fullPath: '/services/peptide-wellness'
      preLoaderRoute: typeof ServicesPeptideWellnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/mental-health': {
      id: '/services_/mental-health'
      path: '/services/mental-health'
      fullPath: '/services/mental-health'
      preLoaderRoute: typeof ServicesMentalHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/medication-management': {
      id: '/services_/medication-management'
      path: '/services/medication-management'
      fullPath: '/services/medication-management'
      preLoaderRoute: typeof ServicesMedicationManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/iop': {
      id: '/services_/iop'
      path: '/services/iop'
      fullPath: '/services/iop'
      preLoaderRoute: typeof ServicesIopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/healthcare-consulting': {
      id: '/services_/healthcare-consulting'
      path: '/services/healthcare-consulting'
      fullPath: '/services/healthcare-consulting'
      preLoaderRoute: typeof ServicesHealthcareConsultingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/coaching-development': {
      id: '/services_/coaching-development'
      path: '/services/coaching-development'
      fullPath: '/services/coaching-development'
      preLoaderRoute: typeof ServicesCoachingDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/coaching': {
      id: '/services_/coaching'
      path: '/services/coaching'
      fullPath: '/services/coaching'
      preLoaderRoute: typeof ServicesCoachingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/clinical': {
      id: '/services_/clinical'
      path: '/services/clinical'
      fullPath: '/services/clinical'
      preLoaderRoute: typeof ServicesClinicalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookingRoute: BookingRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  GetMatchedRoute: GetMatchedRoute,
  IntakeRoute: IntakeRoute,
  JoinTheNetworkRoute: JoinTheNetworkRoute,
  PartnershipsRoute: PartnershipsRoute,
  ProviderApplyRoute: ProviderApplyRoute,
  ProvidersRoute: ProvidersRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VirtualWellnessRoute: VirtualWellnessRoute,
  WaitlistRoute: WaitlistRoute,
  ServicesClinicalRoute: ServicesClinicalRoute,
  ServicesCoachingRoute: ServicesCoachingRoute,
  ServicesCoachingDevelopmentRoute: ServicesCoachingDevelopmentRoute,
  ServicesHealthcareConsultingRoute: ServicesHealthcareConsultingRoute,
  ServicesIopRoute: ServicesIopRoute,
  ServicesMedicationManagementRoute: ServicesMedicationManagementRoute,
  ServicesMentalHealthRoute: ServicesMentalHealthRoute,
  ServicesPeptideWellnessRoute: ServicesPeptideWellnessRoute,
  ServicesProviderPartnershipsRoute: ServicesProviderPartnershipsRoute,
  ServicesTherapyRoute: ServicesTherapyRoute,
  ServicesVirtualBehavioralHealthRoute: ServicesVirtualBehavioralHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
